server.port=8085
spring.application.name=payment-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.waitDurationInOpenState=10s
